// Firebase 초기화 코드(Firebase와 Flutter 프로젝트가 통합되어 Firebase 서비스를 사용가능)
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Lq8c-gIglvsKKVnfF1oC2GPwXxOpTTk',
    appId: '1:858485210134:web:aa4a8ecb38da5da6cd8937',
    messagingSenderId: '858485210134',
    projectId: 'dongdaemoonproject1',
    authDomain: 'dongdaemoonproject1.firebaseapp.com',
    storageBucket: 'dongdaemoonproject1.appspot.com',
    measurementId: 'G-L6MJYTQG6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMD8CaT_VSpJxDhBoGPhSjnz5szomXEs',
    appId: '1:858485210134:android:1a96b517e3788ad5cd8937',
    messagingSenderId: '858485210134',
    projectId: 'dongdaemoonproject1',
    storageBucket: 'dongdaemoonproject1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuAtzywwx7JdwslGGbC74SYboAw1CJy4s',
    appId: '1:858485210134:ios:8f4af15237890620cd8937',
    messagingSenderId: '858485210134',
    projectId: 'dongdaemoonproject1',
    storageBucket: 'dongdaemoonproject1.appspot.com',
    iosBundleId: 'com.example.dongdaemoonBetaV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuAtzywwx7JdwslGGbC74SYboAw1CJy4s',
    appId: '1:858485210134:ios:51397f0be9ad8fbbcd8937',
    messagingSenderId: '858485210134',
    projectId: 'dongdaemoonproject1',
    storageBucket: 'dongdaemoonproject1.appspot.com',
    iosBundleId: 'com.example.dongdaemoonBetaV1.RunnerTests',
  );
}
